# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloud_replay.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'


descriptor_data = "\n\x12\x63loud_replay.proto\x12\x06replay\x1a\x1bgoogle/protobuf/empty.proto\"\x14\n\x12ListReplaysRequest\":\n\x13ListReplaysResponse\x12#\n\x07replays\x18\x01 \x03(\x0b\x32\x12.replay.ReplayInfo\"\x1f\n\nReplayInfo\x12\x11\n\treplay_id\x18\x01 \x01(\t\"O\n\x11LoadReplayRequest\x12\x11\n\treplay_id\x18\x01 \x01(\t\x12\x11\n\troom_name\x18\x02 \x01(\t\x12\x14\n\x0cstarting_pts\x18\x03 \x01(\x03\")\n\x12LoadReplayResponse\x12\x13\n\x0bplayback_id\x18\x01 \x01(\t\"3\n\x0fRoomSeekRequest\x12\x13\n\x0bplayback_id\x18\x01 \x01(\t\x12\x0b\n\x03pts\x18\x02 \x01(\x03\")\n\x12\x43loseReplayRequest\x12\x13\n\x0bplayback_id\x18\x01 \x01(\t\"(\n\x13\x44\x65leteReplayRequest\x12\x11\n\treplay_id\x18\x01 \x01(\t2\xdd\x02\n\x06Replay\x12\x46\n\x0bListReplays\x12\x1a.replay.ListReplaysRequest\x1a\x1b.replay.ListReplaysResponse\x12\x43\n\nLoadReplay\x12\x19.replay.LoadReplayRequest\x1a\x1a.replay.LoadReplayResponse\x12>\n\x0bSeekForRoom\x12\x17.replay.RoomSeekRequest\x1a\x16.google.protobuf.Empty\x12\x41\n\x0b\x43loseReplay\x12\x1a.replay.CloseReplayRequest\x1a\x16.google.protobuf.Empty\x12\x43\n\x0c\x44\x65leteReplay\x12\x1b.replay.DeleteReplayRequest\x1a\x16.google.protobuf.EmptyBEZ\"github.com/livekit/protocol/replay\xaa\x02\rLiveKit.Proto\xea\x02\x0eLiveKit::Protob\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module LiveKit
  module Proto
    ListReplaysRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("replay.ListReplaysRequest").msgclass
    ListReplaysResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("replay.ListReplaysResponse").msgclass
    ReplayInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("replay.ReplayInfo").msgclass
    LoadReplayRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("replay.LoadReplayRequest").msgclass
    LoadReplayResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("replay.LoadReplayResponse").msgclass
    RoomSeekRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("replay.RoomSeekRequest").msgclass
    CloseReplayRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("replay.CloseReplayRequest").msgclass
    DeleteReplayRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("replay.DeleteReplayRequest").msgclass
  end
end
