# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handle.proto

require 'google/protobuf'


descriptor_data = "\n\x0chandle.proto\x12\rlivekit.proto\"\x1c\n\x0e\x46\x66iOwnedHandle\x12\n\n\x02id\x18\x01 \x01(\x04\x42\x10\xaa\x02\rLiveKit.Protob\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Livekit
  module Proto
    FfiOwnedHandle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.proto.FfiOwnedHandle").msgclass
  end
end
