# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: participant.proto

require 'google/protobuf'

require 'handle_pb'


descriptor_data = "\n\x11participant.proto\x12\rlivekit.proto\x1a\x0chandle.proto\"\xf5\x01\n\x0fParticipantInfo\x12\x0b\n\x03sid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08identity\x18\x03 \x01(\t\x12\x10\n\x08metadata\x18\x04 \x01(\t\x12\x42\n\nattributes\x18\x05 \x03(\x0b\x32..livekit.proto.ParticipantInfo.AttributesEntry\x12,\n\x04kind\x18\x06 \x01(\x0e\x32\x1e.livekit.proto.ParticipantKind\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"o\n\x10OwnedParticipant\x12-\n\x06handle\x18\x01 \x01(\x0b\x32\x1d.livekit.proto.FfiOwnedHandle\x12,\n\x04info\x18\x02 \x01(\x0b\x32\x1e.livekit.proto.ParticipantInfo*\xa1\x01\n\x0fParticipantKind\x12\x1d\n\x19PARTICIPANT_KIND_STANDARD\x10\x00\x12\x1c\n\x18PARTICIPANT_KIND_INGRESS\x10\x01\x12\x1b\n\x17PARTICIPANT_KIND_EGRESS\x10\x02\x12\x18\n\x14PARTICIPANT_KIND_SIP\x10\x03\x12\x1a\n\x16PARTICIPANT_KIND_AGENT\x10\x04\x42\x10\xaa\x02\rLiveKit.Protob\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Livekit
  module Proto
    ParticipantInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.proto.ParticipantInfo").msgclass
    OwnedParticipant = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.proto.OwnedParticipant").msgclass
    ParticipantKind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("livekit.proto.ParticipantKind").enummodule
  end
end
